#+title: emacs-dockerfiles
#+author: conao3

[[https://github.com/conao3/emacs-dockerfiles/blob/master/LICENSE][https://img.shields.io/github/license/conao3/emacs-dockerfiles.svg?style=flat-square]]
[[https://github.com/conao3/emacs-dockerfiles/releases][https://img.shields.io/github/tag/conao3/emacs-dockerfiles.svg?style=flat-square]]

* Overview

A collection of Dockerfiles for building Emacs 27.1 from source on various Linux distributions.

This project provides ready-to-use Docker configurations for compiling Emacs with full feature support, including native JSON parsing, dynamic modules, and GTK3 integration.

** Supported Distributions

- Ubuntu 20.04
- Debian
- CentOS
- Arch Linux

* Getting Started

** Prerequisites

- Docker installed on your system
- Basic familiarity with Docker commands

** Building an Image

Clone the repository and build the image for your preferred distribution:

#+begin_src shell
git clone https://github.com/conao3/emacs-dockerfiles.git
cd emacs-dockerfiles

# Build for Ubuntu
docker build -t emacs:27.1-ubuntu -f emacs-27.1/Dockerfile-ubuntu .

# Build for Debian
docker build -t emacs:27.1-debian -f emacs-27.1/Dockerfile-debian .

# Build for CentOS
docker build -t emacs:27.1-centos -f emacs-27.1/Dockerfile-centos .

# Build for Arch Linux
docker build -t emacs:27.1-arch -f emacs-27.1/Dockerfile-arch .
#+end_src

** Running the Container

#+begin_src shell
docker run -it emacs:27.1-ubuntu
#+end_src

* Build Configuration

The Emacs builds are configured with the following features enabled:

- GTK3 toolkit
- Native JSON support (libjansson)
- Dynamic module support
- HarfBuzz text shaping
- GnuTLS encryption
- XML parsing
- Image format support (PNG, JPEG, TIFF, GIF, SVG)
- D-Bus integration
- System notifications via inotify
- Portable dumper

* Editor Configuration

For editing Dockerfiles in Emacs, consider adding this configuration:

#+begin_src emacs-lisp
(use-package dockerfile-mode
  :mode "Dockerfile-[^/]*\\'")
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

* License

MIT License

Copyright (c) Naoya Yamashita

See [[https://github.com/conao3/emacs-dockerfiles/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
