FROM centos:8

MAINTAINER conao3

ENV LC_ALL=C

RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --enable AppStream PowerTools

##############################

ARG USER=user
ARG UID=1000
ARG GID=1000
ARG HOME=/home/${USER}
ARG SHELL=/usr/bin/bash

RUN dnf install -y sudo passwd && \
    groupadd -g ${GID} ${USER} && \
    useradd -u ${UID} -g ${GID} -m -s ${SHELL} ${USER} && \
    passwd -d ${USER} && \
    echo "${USER} ALL=(ALL) ALL" > /etc/sudoers && \
    sed -ie 's/^Defaults\tenv_reset/# Defaults\tenv_reset/' /etc/sudoers && \
    sed -ie 's/^Defaults\tsecure_path/# Defaults\tsecure_path/' /etc/sudoers

##############################

USER ${USER}
WORKDIR ${HOME}

ENV PATH=/home/user/.local/bin:$PATH
ENV EDITOR=emacs
ARG VERSION=27.1

RUN mkdir -p ${HOME}/.local/work && \
    cd ${HOME}/.local/work && \
    curl -LO https://ftp.gnu.org/gnu/emacs/emacs-$VERSION.tar.gz && \
    tar xf emacs-$VERSION.tar.gz

RUN sudo dnf -y groupinstall "Development Tools"

RUN curl https://src.fedoraproject.org/rpms/emacs/raw/f33/f/emacs.spec | \
    sed -e 's/m17n-lib-devel//g' -e 's/libotf-devel//g' | \
    grep ^BuildRequires | cut -d" " -f2 | xargs sudo dnf -y install

RUN cd ${HOME}/.local/work/emacs-$VERSION && \
    ./autogen.sh && \
    ./configure --prefix=$HOME/.local --with-modules && \
    make -j && make install

CMD ["bash"]

# Install below packages
#   alsa-lib-devel atk-devel autoconf bzip2 cairo cairo-devel
#   dbus-devel desktop-file-utils fontconfig-devel freetype-devel
#   gcc giflib-devel glibc-devel gnupg2 gnutls-devel gpm-devel
#   gtk3-devel gzip harfbuzz-devel jansson-devel libacl-devel
#   libjpeg-turbo libjpeg-turbo-devel liblockfile-devel
#   libpng-devel librsvg2-devel libselinux-devel libtiff-devel
#   libX11-devel libXau-devel libXdmcp-devel libxml2-devel
#   libXpm-devel libXrender-devel libXt-devel ncurses-devel
#   systemd-devel texinfo util-linux webkit2gtk3-devel
#   Xaw3d-devel xorg-x11-proto-devel zlib-devel

# Configured for 'x86_64-pc-linux-gnu'.
#   Where should the build process find the source code?    .
#   What compiler should emacs be built with?               gcc -g3 -O2
#   Should Emacs use the GNU version of malloc?             no
#     (The GNU allocators don't work with this system configuration.)
#   Should Emacs use a relocating allocator for buffers?    no
#   Should Emacs use mmap(2) for buffer allocation?         no
#   What window system should Emacs use?                    x11
#   What toolkit should Emacs use?                          GTK3
#   Where do we find X Windows header files?                Standard dirs
#   Where do we find X Windows libraries?                   Standard dirs
#   Does Emacs use -lXaw3d?                                 no
#   Does Emacs use -lXpm?                                   yes
#   Does Emacs use -ljpeg?                                  yes
#   Does Emacs use -ltiff?                                  yes
#   Does Emacs use a gif library?                           yes -lgif
#   Does Emacs use a png library?                           yes -lpng16 -lz 
#   Does Emacs use -lrsvg-2?                                yes
#   Does Emacs use cairo?                                   no
#   Does Emacs use -llcms2?                                 no
#   Does Emacs use imagemagick?                             no
#   Does Emacs support sound?                               yes
#   Does Emacs use -lgpm?                                   yes
#   Does Emacs use -ldbus?                                  yes
#   Does Emacs use -lgconf?                                 no
#   Does Emacs use GSettings?                               yes
#   Does Emacs use a file notification library?             yes -lglibc (inotify)
#   Does Emacs use access control lists?                    yes -lacl
#   Does Emacs use -lselinux?                               yes
#   Does Emacs use -lgnutls?                                yes
#   Does Emacs use -lxml2?                                  yes
#   Does Emacs use -lfreetype?                              yes
#   Does Emacs use HarfBuzz?                                yes
#   Does Emacs use -lm17n-flt?                              no
#   Does Emacs use -lotf?                                   no
#   Does Emacs use -lxft?                                   yes
#   Does Emacs use -lsystemd?                               yes
#   Does Emacs use -ljansson?                               yes
#   Does Emacs use -lgmp?                                   yes
#   Does Emacs directly use zlib?                           yes
#   Does Emacs have dynamic modules support?                yes
#   Does Emacs use toolkit scroll bars?                     yes
#   Does Emacs support Xwidgets (requires gtk3)?            no
#   Does Emacs have threading support in lisp?              yes
#   Does Emacs support the portable dumper?                 yes
#   Does Emacs support legacy unexec dumping?               no
#   Which dumping strategy does Emacs use?                  pdumper
